begin
    comment library 1;
 integer
  i,
  j,
  sum;

 i := 1;
 j := 2;
 sum := 0;
 if i > j then
  begin

  end
 else
  begin
  sum := sum + 1;
  if i > j then
   begin

   end
  else
   begin
   sum := sum + 1;
   if i > j then
    begin

    end
   else
    begin
    sum := sum + 1;
    if i > j then
     begin

     end
    else
     begin
     sum := sum + 1;
     if i > j then
      begin

      end
     else
      begin
      sum := sum + 1;
      if i > j then
       begin

       end
      else
       begin
       sum := sum + 1;
       if i > j then
        begin

        end
       else
        begin
        sum := sum + 1;
        if i > j then
         begin

         end
        else
         begin
         sum := sum + 1;
         if i > j then
          begin

          end
         else
          begin
          sum := sum + 1;
          if i > j then
           begin

           end
          else
           begin
           sum := sum + 1;
           if i > j then
            begin

            end
           else
            begin
            sum := sum + 1;
            if i > j then
             begin

             end
            else
             begin
             sum := sum + 1;
             if i > j then
              begin

              end
             else
              begin
              sum := sum + 1;
              if i > j then
               begin

               end
              else
               begin
               sum := sum + 1;
               if i > j then
                begin

                end
               else
                begin
                sum := sum + 1;
                if i > j then
                 begin

                 end
                else
                 begin
                 sum := sum + 1;
                 if i > j then
                  begin

                  end
                 else
                  begin
                  sum := sum + 1;
                  if i > j then
                   begin

                   end
                  else
                   begin
                   sum := sum + 1;
                   if i > j then
                    begin

                    end
                   else
                    begin
                    sum := sum + 1;
                    if i > j then
                     begin

                     end
                    else
                     begin
                     sum := sum + 1;
                     if i > j then
                      begin

                      end
                     else
                      begin
                      sum := sum + 1;
                      if i > j then
                       begin

                       end
                      else
                       begin
                       sum := sum + 1;
                       if i > j then
                        begin

                        end
                       else
                        begin
                        sum := sum + 1;
                        if i > j then
                         begin

                         end
                        else
                         begin
                         sum := sum + 1;
                         end
                        end
                       end
                      end
                     end
                    end
                   end
                  end
                 end
                end
               end
              end
             end
            end
           end
          end
         end
        end
       end
      end
     end
    end
   end
  end;

 outreal(1, sum);


end
