begin

  comment library 1;

  integer
    sum;
  sum := 0;
  begin
    sum := sum + 1;
    begin
      sum := sum + 1;
      begin
        sum := sum + 1;
        begin
          sum := sum + 1;
          begin
            sum := sum + 1;
            begin
              sum := sum + 1;
              begin
                sum := sum + 1;
                begin
                  sum := sum + 1;
                  begin
                    sum := sum + 1;
                    begin
                      sum := sum + 1;
                      begin
                        sum := sum + 1;
                        begin
                          sum := sum + 1;
                          begin
                            sum := sum + 1;
                            begin
                              sum := sum + 1;
                              begin
                                sum := sum + 1;
                                begin
                                  sum := sum + 1;
                                  begin
                                    sum := sum + 1;
                                    begin
                                      sum := sum + 1;
                                      begin
                                        sum := sum + 1;
                                        begin
                                          sum := sum + 1;
                                          begin
                                            sum := sum + 1;
                                            begin
                                              sum := sum + 1;
                                              begin
                                                sum := sum + 1;
                                                begin
                                                  sum := sum + 1;
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end;
  outreal(1, sum);
end
