begin
comment library5;
    real
        r;
    Boolean
        b;
    integer procedure f(x);
        real
            x;
        f := 0;

    integer
        i,
        n,
        s;
    integer procedure g(y);
        Boolean
            y;
        g :=
            if y then
                2
            else
                3;

    r := 3.5;
    n := 4;
    s := r + (1) + n;
    outreal(1, s);
    begin
        real array
            ra[f(if true then 0 else 0) : 1];
        array
            a[ - 1 : f(0)];
        real procedure q;
            q := r^2;

        s :=
            if + 0 = 0 then
                sqrt(q)
            else
                1
    end;
    outreal(1, s);
    begin
        procedure w(t, u);
            string
                t,
                u;
            ;

        w( " a real ", " b end " );
        for i := 0 do

    end;
    if 2 = 2 then
        begin
        i := 1
        end
    else
        i := 0;
    for i := 5 while r < n do
        c : begin
        b := true;
        n :=
            if b | ! b then
                g(b | b) % s
            else
                10;
        b :=
            if b then
                false | false
            else
                true;
        r := n / 2
        end;
    outreal(1, n);
end
