begin

    comment library 1;

    switch ss :=
        a0,
        a1,
        a2,
        a3,
        a4,
        a5,
        a6,
        a7,
        a8,
        a9,
        a10,
        a11,
        a12,
        a13,
        a14,
        a15,
        a16,
        a17,
        a18,
        a19,
        a20,
        a21,
        a22,
        a23,
        a24,
        a25,
        a26,
        a27,
        a28,
        a29,
        a30,
        a31,
        a32,
        a33,
        a34,
        a35,
        a36,
        a37,
        a38,
        a39,
        a40,
        a41,
        a42,
        a43,
        a44,
        a45,
        a46,
        a47,
        a48,
        a49,
        a50,
        a51,
        a52,
        a53,
        a54,
        a55,
        a56,
        a57,
        a58,
        a59,
        a60,
        a61,
        a62,
        a63,
        a64,
        a65,
        a66,
        a67,
        a68,
        a69,
        a70,
        a71,
        a72,
        a73,
        a74,
        a75,
        a76,
        a77,
        a78,
        a79,
        a80,
        a81,
        a82,
        a83,
        a84,
        a85,
        a86,
        a87,
        a88,
        a89,
        a90,
        a91,
        a92,
        a93,
        a94,
        a95,
        a96,
        a97,
        a98,
        a99,
        a100,
        a101,
        a102,
        a103,
        a104,
        a105,
        a106,
        a107,
        a108,
        a109,
        a110,
        a111,
        a112,
        a113,
        a114,
        a115,
        a116,
        a117,
        a118,
        a119,
        a120,
        a121,
        a122,
        a123,
        a124,
        a125,
        a126,
        a127,
        a128,
        a129,
        a130,
        a131,
        a132,
        a133,
        a134,
        a135,
        a136,
        a137,
        a138,
        a139,
        a140,
        a141,
        a142,
        a143,
        a144,
        a145,
        a146,
        a147,
        a148,
        a149,
        a150,
        a151,
        a152,
        a153,
        a154,
        a155,
        a156,
        a157,
        a158,
        a159,
        a160,
        a161,
        a162,
        a163,
        a164,
        a165,
        a166,
        a167,
        a168,
        a169,
        a170,
        a171,
        a172,
        a173,
        a174,
        a175,
        a176,
        a177,
        a178,
        a179,
        a180,
        a181,
        a182,
        a183,
        a184,
        a185,
        a186,
        a187,
        a188,
        a189,
        a190,
        a191,
        a192,
        a193,
        a194,
        a195,
        a196,
        a197,
        a198,
        a199,
        a200,
        a201,
        a202,
        a203,
        a204,
        a205,
        a206,
        a207,
        a208,
        a209,
        a210,
        a211,
        a212,
        a213,
        a214,
        a215,
        a216,
        a217,
        a218,
        a219,
        a220,
        a221,
        a222,
        a223,
        a224,
        a225,
        a226,
        a227,
        a228,
        a229,
        a230,
        a231,
        a232,
        a233,
        a234,
        a235,
        a236,
        a237,
        a238,
        a239,
        a240,
        a241,
        a242,
        a243,
        a244,
        a245,
        a246,
        a247,
        a248,
        a249,
        a250,
        a251,
        a252,
        a253,
        a254,
        a255,
        a256,
        a257,
        a258,
        a259,
        a260,
        a261,
        a262,
        a263,
        a264,
        a265,
        a266,
        a267,
        a268,
        a269,
        a270,
        a271,
        a272,
        a273,
        a274,
        a275,
        a276,
        a277,
        a278,
        a279,
        a280,
        a281,
        a282,
        a283,
        a284,
        a285,
        a286,
        a287,
        a288,
        a289,
        a290,
        a291,
        a292,
        a293,
        a294,
        a295,
        a296,
        a297,
        a298,
        a299;
    integer
        sum;
    sum := 1;
    a0 :;
    sum := sum + 1;
    go to ss[sum];
    a1 :;
    sum := sum + 1;
    go to ss[sum];
    a2 :;
    sum := sum + 1;
    go to ss[sum];
    a3 :;
    sum := sum + 1;
    go to ss[sum];
    a4 :;
    sum := sum + 1;
    go to ss[sum];
    a5 :;
    sum := sum + 1;
    go to ss[sum];
    a6 :;
    sum := sum + 1;
    go to ss[sum];
    a7 :;
    sum := sum + 1;
    go to ss[sum];
    a8 :;
    sum := sum + 1;
    go to ss[sum];
    a9 :;
    sum := sum + 1;
    go to ss[sum];
    a10 :;
    sum := sum + 1;
    go to ss[sum];
    a11 :;
    sum := sum + 1;
    go to ss[sum];
    a12 :;
    sum := sum + 1;
    go to ss[sum];
    a13 :;
    sum := sum + 1;
    go to ss[sum];
    a14 :;
    sum := sum + 1;
    go to ss[sum];
    a15 :;
    sum := sum + 1;
    go to ss[sum];
    a16 :;
    sum := sum + 1;
    go to ss[sum];
    a17 :;
    sum := sum + 1;
    go to ss[sum];
    a18 :;
    sum := sum + 1;
    go to ss[sum];
    a19 :;
    sum := sum + 1;
    go to ss[sum];
    a20 :;
    sum := sum + 1;
    go to ss[sum];
    a21 :;
    sum := sum + 1;
    go to ss[sum];
    a22 :;
    sum := sum + 1;
    go to ss[sum];
    a23 :;
    sum := sum + 1;
    go to ss[sum];
    a24 :;
    sum := sum + 1;
    go to ss[sum];
    a25 :;
    sum := sum + 1;
    go to ss[sum];
    a26 :;
    sum := sum + 1;
    go to ss[sum];
    a27 :;
    sum := sum + 1;
    go to ss[sum];
    a28 :;
    sum := sum + 1;
    go to ss[sum];
    a29 :;
    sum := sum + 1;
    go to ss[sum];
    a30 :;
    sum := sum + 1;
    go to ss[sum];
    a31 :;
    sum := sum + 1;
    go to ss[sum];
    a32 :;
    sum := sum + 1;
    go to ss[sum];
    a33 :;
    sum := sum + 1;
    go to ss[sum];
    a34 :;
    sum := sum + 1;
    go to ss[sum];
    a35 :;
    sum := sum + 1;
    go to ss[sum];
    a36 :;
    sum := sum + 1;
    go to ss[sum];
    a37 :;
    sum := sum + 1;
    go to ss[sum];
    a38 :;
    sum := sum + 1;
    go to ss[sum];
    a39 :;
    sum := sum + 1;
    go to ss[sum];
    a40 :;
    sum := sum + 1;
    go to ss[sum];
    a41 :;
    sum := sum + 1;
    go to ss[sum];
    a42 :;
    sum := sum + 1;
    go to ss[sum];
    a43 :;
    sum := sum + 1;
    go to ss[sum];
    a44 :;
    sum := sum + 1;
    go to ss[sum];
    a45 :;
    sum := sum + 1;
    go to ss[sum];
    a46 :;
    sum := sum + 1;
    go to ss[sum];
    a47 :;
    sum := sum + 1;
    go to ss[sum];
    a48 :;
    sum := sum + 1;
    go to ss[sum];
    a49 :;
    sum := sum + 1;
    go to ss[sum];
    a50 :;
    sum := sum + 1;
    go to ss[sum];
    a51 :;
    sum := sum + 1;
    go to ss[sum];
    a52 :;
    sum := sum + 1;
    go to ss[sum];
    a53 :;
    sum := sum + 1;
    go to ss[sum];
    a54 :;
    sum := sum + 1;
    go to ss[sum];
    a55 :;
    sum := sum + 1;
    go to ss[sum];
    a56 :;
    sum := sum + 1;
    go to ss[sum];
    a57 :;
    sum := sum + 1;
    go to ss[sum];
    a58 :;
    sum := sum + 1;
    go to ss[sum];
    a59 :;
    sum := sum + 1;
    go to ss[sum];
    a60 :;
    sum := sum + 1;
    go to ss[sum];
    a61 :;
    sum := sum + 1;
    go to ss[sum];
    a62 :;
    sum := sum + 1;
    go to ss[sum];
    a63 :;
    sum := sum + 1;
    go to ss[sum];
    a64 :;
    sum := sum + 1;
    go to ss[sum];
    a65 :;
    sum := sum + 1;
    go to ss[sum];
    a66 :;
    sum := sum + 1;
    go to ss[sum];
    a67 :;
    sum := sum + 1;
    go to ss[sum];
    a68 :;
    sum := sum + 1;
    go to ss[sum];
    a69 :;
    sum := sum + 1;
    go to ss[sum];
    a70 :;
    sum := sum + 1;
    go to ss[sum];
    a71 :;
    sum := sum + 1;
    go to ss[sum];
    a72 :;
    sum := sum + 1;
    go to ss[sum];
    a73 :;
    sum := sum + 1;
    go to ss[sum];
    a74 :;
    sum := sum + 1;
    go to ss[sum];
    a75 :;
    sum := sum + 1;
    go to ss[sum];
    a76 :;
    sum := sum + 1;
    go to ss[sum];
    a77 :;
    sum := sum + 1;
    go to ss[sum];
    a78 :;
    sum := sum + 1;
    go to ss[sum];
    a79 :;
    sum := sum + 1;
    go to ss[sum];
    a80 :;
    sum := sum + 1;
    go to ss[sum];
    a81 :;
    sum := sum + 1;
    go to ss[sum];
    a82 :;
    sum := sum + 1;
    go to ss[sum];
    a83 :;
    sum := sum + 1;
    go to ss[sum];
    a84 :;
    sum := sum + 1;
    go to ss[sum];
    a85 :;
    sum := sum + 1;
    go to ss[sum];
    a86 :;
    sum := sum + 1;
    go to ss[sum];
    a87 :;
    sum := sum + 1;
    go to ss[sum];
    a88 :;
    sum := sum + 1;
    go to ss[sum];
    a89 :;
    sum := sum + 1;
    go to ss[sum];
    a90 :;
    sum := sum + 1;
    go to ss[sum];
    a91 :;
    sum := sum + 1;
    go to ss[sum];
    a92 :;
    sum := sum + 1;
    go to ss[sum];
    a93 :;
    sum := sum + 1;
    go to ss[sum];
    a94 :;
    sum := sum + 1;
    go to ss[sum];
    a95 :;
    sum := sum + 1;
    go to ss[sum];
    a96 :;
    sum := sum + 1;
    go to ss[sum];
    a97 :;
    sum := sum + 1;
    go to ss[sum];
    a98 :;
    sum := sum + 1;
    go to ss[sum];
    a99 :;
    sum := sum + 1;
    go to ss[sum];
    a100 :;
    sum := sum + 1;
    go to ss[sum];
    a101 :;
    sum := sum + 1;
    go to ss[sum];
    a102 :;
    sum := sum + 1;
    go to ss[sum];
    a103 :;
    sum := sum + 1;
    go to ss[sum];
    a104 :;
    sum := sum + 1;
    go to ss[sum];
    a105 :;
    sum := sum + 1;
    go to ss[sum];
    a106 :;
    sum := sum + 1;
    go to ss[sum];
    a107 :;
    sum := sum + 1;
    go to ss[sum];
    a108 :;
    sum := sum + 1;
    go to ss[sum];
    a109 :;
    sum := sum + 1;
    go to ss[sum];
    a110 :;
    sum := sum + 1;
    go to ss[sum];
    a111 :;
    sum := sum + 1;
    go to ss[sum];
    a112 :;
    sum := sum + 1;
    go to ss[sum];
    a113 :;
    sum := sum + 1;
    go to ss[sum];
    a114 :;
    sum := sum + 1;
    go to ss[sum];
    a115 :;
    sum := sum + 1;
    go to ss[sum];
    a116 :;
    sum := sum + 1;
    go to ss[sum];
    a117 :;
    sum := sum + 1;
    go to ss[sum];
    a118 :;
    sum := sum + 1;
    go to ss[sum];
    a119 :;
    sum := sum + 1;
    go to ss[sum];
    a120 :;
    sum := sum + 1;
    go to ss[sum];
    a121 :;
    sum := sum + 1;
    go to ss[sum];
    a122 :;
    sum := sum + 1;
    go to ss[sum];
    a123 :;
    sum := sum + 1;
    go to ss[sum];
    a124 :;
    sum := sum + 1;
    go to ss[sum];
    a125 :;
    sum := sum + 1;
    go to ss[sum];
    a126 :;
    sum := sum + 1;
    go to ss[sum];
    a127 :;
    sum := sum + 1;
    go to ss[sum];
    a128 :;
    sum := sum + 1;
    go to ss[sum];
    a129 :;
    sum := sum + 1;
    go to ss[sum];
    a130 :;
    sum := sum + 1;
    go to ss[sum];
    a131 :;
    sum := sum + 1;
    go to ss[sum];
    a132 :;
    sum := sum + 1;
    go to ss[sum];
    a133 :;
    sum := sum + 1;
    go to ss[sum];
    a134 :;
    sum := sum + 1;
    go to ss[sum];
    a135 :;
    sum := sum + 1;
    go to ss[sum];
    a136 :;
    sum := sum + 1;
    go to ss[sum];
    a137 :;
    sum := sum + 1;
    go to ss[sum];
    a138 :;
    sum := sum + 1;
    go to ss[sum];
    a139 :;
    sum := sum + 1;
    go to ss[sum];
    a140 :;
    sum := sum + 1;
    go to ss[sum];
    a141 :;
    sum := sum + 1;
    go to ss[sum];
    a142 :;
    sum := sum + 1;
    go to ss[sum];
    a143 :;
    sum := sum + 1;
    go to ss[sum];
    a144 :;
    sum := sum + 1;
    go to ss[sum];
    a145 :;
    sum := sum + 1;
    go to ss[sum];
    a146 :;
    sum := sum + 1;
    go to ss[sum];
    a147 :;
    sum := sum + 1;
    go to ss[sum];
    a148 :;
    sum := sum + 1;
    go to ss[sum];
    a149 :;
    sum := sum + 1;
    go to ss[sum];
    a150 :;
    sum := sum + 1;
    go to ss[sum];
    a151 :;
    sum := sum + 1;
    go to ss[sum];
    a152 :;
    sum := sum + 1;
    go to ss[sum];
    a153 :;
    sum := sum + 1;
    go to ss[sum];
    a154 :;
    sum := sum + 1;
    go to ss[sum];
    a155 :;
    sum := sum + 1;
    go to ss[sum];
    a156 :;
    sum := sum + 1;
    go to ss[sum];
    a157 :;
    sum := sum + 1;
    go to ss[sum];
    a158 :;
    sum := sum + 1;
    go to ss[sum];
    a159 :;
    sum := sum + 1;
    go to ss[sum];
    a160 :;
    sum := sum + 1;
    go to ss[sum];
    a161 :;
    sum := sum + 1;
    go to ss[sum];
    a162 :;
    sum := sum + 1;
    go to ss[sum];
    a163 :;
    sum := sum + 1;
    go to ss[sum];
    a164 :;
    sum := sum + 1;
    go to ss[sum];
    a165 :;
    sum := sum + 1;
    go to ss[sum];
    a166 :;
    sum := sum + 1;
    go to ss[sum];
    a167 :;
    sum := sum + 1;
    go to ss[sum];
    a168 :;
    sum := sum + 1;
    go to ss[sum];
    a169 :;
    sum := sum + 1;
    go to ss[sum];
    a170 :;
    sum := sum + 1;
    go to ss[sum];
    a171 :;
    sum := sum + 1;
    go to ss[sum];
    a172 :;
    sum := sum + 1;
    go to ss[sum];
    a173 :;
    sum := sum + 1;
    go to ss[sum];
    a174 :;
    sum := sum + 1;
    go to ss[sum];
    a175 :;
    sum := sum + 1;
    go to ss[sum];
    a176 :;
    sum := sum + 1;
    go to ss[sum];
    a177 :;
    sum := sum + 1;
    go to ss[sum];
    a178 :;
    sum := sum + 1;
    go to ss[sum];
    a179 :;
    sum := sum + 1;
    go to ss[sum];
    a180 :;
    sum := sum + 1;
    go to ss[sum];
    a181 :;
    sum := sum + 1;
    go to ss[sum];
    a182 :;
    sum := sum + 1;
    go to ss[sum];
    a183 :;
    sum := sum + 1;
    go to ss[sum];
    a184 :;
    sum := sum + 1;
    go to ss[sum];
    a185 :;
    sum := sum + 1;
    go to ss[sum];
    a186 :;
    sum := sum + 1;
    go to ss[sum];
    a187 :;
    sum := sum + 1;
    go to ss[sum];
    a188 :;
    sum := sum + 1;
    go to ss[sum];
    a189 :;
    sum := sum + 1;
    go to ss[sum];
    a190 :;
    sum := sum + 1;
    go to ss[sum];
    a191 :;
    sum := sum + 1;
    go to ss[sum];
    a192 :;
    sum := sum + 1;
    go to ss[sum];
    a193 :;
    sum := sum + 1;
    go to ss[sum];
    a194 :;
    sum := sum + 1;
    go to ss[sum];
    a195 :;
    sum := sum + 1;
    go to ss[sum];
    a196 :;
    sum := sum + 1;
    go to ss[sum];
    a197 :;
    sum := sum + 1;
    go to ss[sum];
    a198 :;
    sum := sum + 1;
    go to ss[sum];
    a199 :;
    sum := sum + 1;
    go to ss[sum];
    a200 :;
    sum := sum + 1;
    go to ss[sum];
    a201 :;
    sum := sum + 1;
    go to ss[sum];
    a202 :;
    sum := sum + 1;
    go to ss[sum];
    a203 :;
    sum := sum + 1;
    go to ss[sum];
    a204 :;
    sum := sum + 1;
    go to ss[sum];
    a205 :;
    sum := sum + 1;
    go to ss[sum];
    a206 :;
    sum := sum + 1;
    go to ss[sum];
    a207 :;
    sum := sum + 1;
    go to ss[sum];
    a208 :;
    sum := sum + 1;
    go to ss[sum];
    a209 :;
    sum := sum + 1;
    go to ss[sum];
    a210 :;
    sum := sum + 1;
    go to ss[sum];
    a211 :;
    sum := sum + 1;
    go to ss[sum];
    a212 :;
    sum := sum + 1;
    go to ss[sum];
    a213 :;
    sum := sum + 1;
    go to ss[sum];
    a214 :;
    sum := sum + 1;
    go to ss[sum];
    a215 :;
    sum := sum + 1;
    go to ss[sum];
    a216 :;
    sum := sum + 1;
    go to ss[sum];
    a217 :;
    sum := sum + 1;
    go to ss[sum];
    a218 :;
    sum := sum + 1;
    go to ss[sum];
    a219 :;
    sum := sum + 1;
    go to ss[sum];
    a220 :;
    sum := sum + 1;
    go to ss[sum];
    a221 :;
    sum := sum + 1;
    go to ss[sum];
    a222 :;
    sum := sum + 1;
    go to ss[sum];
    a223 :;
    sum := sum + 1;
    go to ss[sum];
    a224 :;
    sum := sum + 1;
    go to ss[sum];
    a225 :;
    sum := sum + 1;
    go to ss[sum];
    a226 :;
    sum := sum + 1;
    go to ss[sum];
    a227 :;
    sum := sum + 1;
    go to ss[sum];
    a228 :;
    sum := sum + 1;
    go to ss[sum];
    a229 :;
    sum := sum + 1;
    go to ss[sum];
    a230 :;
    sum := sum + 1;
    go to ss[sum];
    a231 :;
    sum := sum + 1;
    go to ss[sum];
    a232 :;
    sum := sum + 1;
    go to ss[sum];
    a233 :;
    sum := sum + 1;
    go to ss[sum];
    a234 :;
    sum := sum + 1;
    go to ss[sum];
    a235 :;
    sum := sum + 1;
    go to ss[sum];
    a236 :;
    sum := sum + 1;
    go to ss[sum];
    a237 :;
    sum := sum + 1;
    go to ss[sum];
    a238 :;
    sum := sum + 1;
    go to ss[sum];
    a239 :;
    sum := sum + 1;
    go to ss[sum];
    a240 :;
    sum := sum + 1;
    go to ss[sum];
    a241 :;
    sum := sum + 1;
    go to ss[sum];
    a242 :;
    sum := sum + 1;
    go to ss[sum];
    a243 :;
    sum := sum + 1;
    go to ss[sum];
    a244 :;
    sum := sum + 1;
    go to ss[sum];
    a245 :;
    sum := sum + 1;
    go to ss[sum];
    a246 :;
    sum := sum + 1;
    go to ss[sum];
    a247 :;
    sum := sum + 1;
    go to ss[sum];
    a248 :;
    sum := sum + 1;
    go to ss[sum];
    a249 :;
    sum := sum + 1;
    go to ss[sum];
    a250 :;
    sum := sum + 1;
    go to ss[sum];
    a251 :;
    sum := sum + 1;
    go to ss[sum];
    a252 :;
    sum := sum + 1;
    go to ss[sum];
    a253 :;
    sum := sum + 1;
    go to ss[sum];
    a254 :;
    sum := sum + 1;
    go to ss[sum];
    a255 :;
    sum := sum + 1;
    go to ss[sum];
    a256 :;
    sum := sum + 1;
    go to ss[sum];
    a257 :;
    sum := sum + 1;
    go to ss[sum];
    a258 :;
    sum := sum + 1;
    go to ss[sum];
    a259 :;
    sum := sum + 1;
    go to ss[sum];
    a260 :;
    sum := sum + 1;
    go to ss[sum];
    a261 :;
    sum := sum + 1;
    go to ss[sum];
    a262 :;
    sum := sum + 1;
    go to ss[sum];
    a263 :;
    sum := sum + 1;
    go to ss[sum];
    a264 :;
    sum := sum + 1;
    go to ss[sum];
    a265 :;
    sum := sum + 1;
    go to ss[sum];
    a266 :;
    sum := sum + 1;
    go to ss[sum];
    a267 :;
    sum := sum + 1;
    go to ss[sum];
    a268 :;
    sum := sum + 1;
    go to ss[sum];
    a269 :;
    sum := sum + 1;
    go to ss[sum];
    a270 :;
    sum := sum + 1;
    go to ss[sum];
    a271 :;
    sum := sum + 1;
    go to ss[sum];
    a272 :;
    sum := sum + 1;
    go to ss[sum];
    a273 :;
    sum := sum + 1;
    go to ss[sum];
    a274 :;
    sum := sum + 1;
    go to ss[sum];
    a275 :;
    sum := sum + 1;
    go to ss[sum];
    a276 :;
    sum := sum + 1;
    go to ss[sum];
    a277 :;
    sum := sum + 1;
    go to ss[sum];
    a278 :;
    sum := sum + 1;
    go to ss[sum];
    a279 :;
    sum := sum + 1;
    go to ss[sum];
    a280 :;
    sum := sum + 1;
    go to ss[sum];
    a281 :;
    sum := sum + 1;
    go to ss[sum];
    a282 :;
    sum := sum + 1;
    go to ss[sum];
    a283 :;
    sum := sum + 1;
    go to ss[sum];
    a284 :;
    sum := sum + 1;
    go to ss[sum];
    a285 :;
    sum := sum + 1;
    go to ss[sum];
    a286 :;
    sum := sum + 1;
    go to ss[sum];
    a287 :;
    sum := sum + 1;
    go to ss[sum];
    a288 :;
    sum := sum + 1;
    go to ss[sum];
    a289 :;
    sum := sum + 1;
    go to ss[sum];
    a290 :;
    sum := sum + 1;
    go to ss[sum];
    a291 :;
    sum := sum + 1;
    go to ss[sum];
    a292 :;
    sum := sum + 1;
    go to ss[sum];
    a293 :;
    sum := sum + 1;
    go to ss[sum];
    a294 :;
    sum := sum + 1;
    go to ss[sum];
    a295 :;
    sum := sum + 1;
    go to ss[sum];
    a296 :;
    sum := sum + 1;
    go to ss[sum];
    a297 :;
    sum := sum + 1;
    go to ss[sum];
    a298 :;
    sum := sum + 1;
    go to ss[sum];
    a299 :;
    sum := sum + 1;
    outreal(1, sum);
end
