begin

    comment   et comment;


    comment library 1;

    real
        c;
    array
        d[ - 0 : + 1, 0#0 : 1.0];
    integer procedure r(c);
        real
            c;
        r :=
            if true then
                c
            else
                r(0);

    d[0, 0] := c := c := 1;
    begin
        real procedure p;
            begin
            q(a, b, c, a[1])encore : (b[1], (1));
            for c := 1 step 1 until if false then p
                    else 1 do
                for c := 1,
                    2 do
                    ;
            p := (0)
            end :p;

        switch b :=
            (b[2]),
            l,
            if if a[1] = 0 & ! false then true
                else false then b[a[1] + 1] else l;
        integer array
            h,
            a[1 : c + d[0, 1 - (r( + 1))]],
            j[0 : 1];
        procedure q(a, b, c, d)e : (e, f);
            integer
                f;
            switch
                b;
            integer array
                a;
            real
                c;
            real
                d;
            label
                e;
            ;


        comment   begin comment end;

        a[1] := 0;
        l :;
        outreal(1, p);
        c := c + 1 * 1^1;
        if c = 2 then
            go to b[p + 3]
    end
end
