begin
    procedure a0;
        begin
        procedure a1;
            begin
            procedure a2;
                begin
                procedure a3;
                    begin
                    procedure a4;
                        begin
                        procedure a5;
                            begin

                            end;

                        ;
                        end;

                    ;
                    end;

                ;
                end;

            ;
            end;

        ;
        end;

    ;
end
