begin

    comment library 1;

    real
        a0,
        a1,
        a2,
        a3,
        a4,
        a5,
        a6,
        a7,
        a8,
        a9,
        a10,
        a11,
        a12,
        a13,
        a14;
    a0 := a1 := a2 := a3 := a4 := a5 := a6 := a7 := a8 :=
        a9 := a10 := a11 := a12 := a13 := a14 := 1.0;
    outreal(1, a0 + a1 + a2 + a3 + a4 + a5 + a6 + a7 + a8 + a9 + a10
        + a11 + a12 + a13 + a14);
end
