begin

    comment library 1;

    integer
        j,
        k,
        s;
    integer procedure f(n);
        value
            n;
        integer
            n;
        begin
        integer
            i,
            l;
        for i := n,
            s % 2 while s < 16 | s = 28 do
            begin
            s := s + i + n;
            l := i
            end;
        f := n + l;
        end f;

    s := - 1;
    for j := f(2),
        f(3) while s = 97 do
        begin
        s := s + f(5) + j + s;
        k := j
        end;
    s := s + k;
    outreal(1, s)
end
