begin

    comment lib 1;

    integer
        s;
    procedure p(f, g);
        procedure
            f,
            g;
        begin
        integer
            x;
        procedure r;
            begin
            outreal(1, s);
            outreal(1, x)
            end;

        s := s + 1;
        x := s;
        if s = 1 then
            p(f, r)
        else
            f(g, r)
        end p;

    procedure q(f, g);
        procedure
            f,
            g;
        begin
        f;
        g
        end q;

    s := 0;
    p(q, p);
end
