begin
    integer
        i;
    real
        r;
    Boolean
        b;
    array
        a1[1 : i + b],
        a2[2 : 4, 5 : 7];
    switch s :=
        if r * p0 < 0 then l else l2;
    procedure p0;
        r := i % r;

    procedure p1(f);
        real
            f;
        b := i + r;

    l :;
    b := i > s;
    b := b | p0;
    r := b + a1;
    l2 :;
    r := b & b;
    i := p1(r);
    go to b;
    i;
    p1(a2 / r);
    r[i] := 5;
    i :=
        if b then
            s
        else
            r;
    p1(if b then b else i - i);
    r := b := b & b;
    for i := b step 1 until r do
        a1[s] := a2[2];
    a1 := 0;
    if r then
        go to l;
    for p0 := 1,
        2 do
        a2[b, i] := 0;
    begin
        array
            q[b : 1];

    end;
    p1(i, r);
    p1;
end
