prog :

begin
comment library 1;
    procedure q;
        begin
        array
            a,
            d[1 : 1, 1 : n],
            e[0 : 0];
        procedure p(x, l);
            label
                l;
            integer procedure
                x;
            b : for i := 1 step 1 until n,
                i + 1 do
                c : go to
                    if x(a[1, 1] + i, 0) = 0 then
                        l
                    else
                        r;

        m :;
        a[1, 1] := n;
        p(in, prog)
        end q;

    integer procedure in(f, g);
        value
            f;
        real
            f,
            g;
        n := in := 1;

    integer
        n,
        i;
    n := 2;
    outreal(1, 1);
    q;
    outreal(1, 2);
    r :;
    outreal(1, 3);
end
